Добавление японской еды | Адаптация.
Corvax-Frontier/Frontier pull request #70
Opened 2024-11-01 09:48 UTC by Chocosasel

Добро пожаловать в уголок вкусной японской культуры. ⛩️

![2024-11-01_11 03 14](https://github.com/user-attachments/assets/90106528-34ca-4363-9a1f-2709b1af2f5a)

### Для чего нужен данный PR? 
Данный PR добавляет японские блюда и сладости, стараясь соблюдать классическую рецептуру. 
Он признан внести разнообразие в блюда, а ещё мне всегда хотелось открыть свою милую лапшичную :3

### Показ блюд. 
### 1. Рамэны 🍜

Начнём с самого главного, а именно рамэн. PR добавляет два новых вида рамэна.
Свиной обычный и свиной острый. Для того что бы приготовить рамэн, вам как не парадоксально...

Нужна заготовка лапша!

![2](https://github.com/user-attachments/assets/f8a8e01c-fc17-4773-91ea-c6a02a5bde49)

Рецепт: 
Мука: [10u]
Столовая соль: [5u]
Оливковое масло: [5u]
Сырое яйцо: [5u]
Вода: [5u]
Тщательно всё перемешайте в удобной вам таре или миске, после чего получите вашу заготовку для рамэна!

Теперь приступим непосредственно к готовке нашего первого рамэна. Первый на очереди...
### Классический свиной рамэн.

![3](https://github.com/user-attachments/assets/56250291-5962-4c8d-8e04-ec475db9b394)

Рецепт: 
Вода: [15u]
Сырое яйцо: [6u]
Сырая котлета: 3 штуки
Миска: 1 штука.
Чеснок: 1 штука.
Сырая лапша для рамэна: 1 штука.
Время приготовления: 15 секунд | Духовка.

![4](https://github.com/user-attachments/assets/b955c100-1a7b-4225-b3f7-5ed074904d1c)

Добавляем в миску воды, варим яйцо отдельно ( вбиваем в миску ) и выкладываем наши ингредиенты в миску и отправляем на плиту. Как только рамэн и яйцо закипят, чистив варенное яйцо, режем долькой и выкладываем сверху
( Давайте представим, что вы варите её сверху на миске, хорошо? ) 
Как предусмотрительно, что сразу после приготовления вы добавили удобные палочки для того, что бы можно было спокойно употребить лапшу. Вы замечательный лапшист!

Если ваши клиенты желают чего более острого, кроме ваших оскорблений? Тогда и для них есть...

### Острый свиной рамэн.

![123](https://github.com/user-attachments/assets/d1256f23-726e-4101-ae10-4e69131ebe48)

Рецепт: 
Вода: [15u]
Сырое яйцо: [6u]
Острый соус: [5u]
Сырая котлета: 3 штуки
Миска: 1 штука.
Чеснок: 1 штука.
Перец чили: 1 штука
Сырая лапша для рамэна: 1 штука.
Время приготовления: 20 секунд | Духовка.

![5](https://github.com/user-attachments/assets/273c4b9f-26e7-4196-a718-e8941c1b84d9)

Практически ничего не меняется из прошлого рецепта, за небольшим исключением. Теперь помимо воды и яйца, в миску добавляется самый острый соус из халапеньо, а так же перец чили. 
Отправляем всю эту красоту на плиту и получаем оружие для любой ротовой полости в секторе!

### 2. Данго 🍡

Вот мы и добрались до традиционной японской сладости.  Так же как и с рамэном, для рисовых шариков нам нужно обязательно слепить шарики из рисовой муки, желательно специализированной. Поэтому начнёт с заготовки...

### Круглое тесто для данго.

![6](https://github.com/user-attachments/assets/7cbff554-2990-40b0-96d3-3a2fc55f2464)

Рецепт: 
Рис: [5u]
Сахар: [5u]
Вода: [5u]
Берём миску, добавляем рисовую муку, заливаем постепенно водой и замешиваем. 
Во время замеса не забываем добавить сахара для того, что бы наш десерт был десертом, а не рисовым пельменем!
Сделай таких шариков три штуки и переходим к следующему этапу!

### Митараши данго.

![7](https://github.com/user-attachments/assets/5ab66cbf-10c7-4a6a-8d4c-f26899c8791a)

Рецепт: 
Соевый соус: [5u]
Сахар: [5u]
Шарик данго: 3 штуки.
Время приготовление: 10 секунд | Духовка.

![8](https://github.com/user-attachments/assets/bc09f17f-10ba-4b86-99ab-13515ca26f35)

Самый классический и традиционный рецепт. Отвариваем наши шарики данго и во время этого на сковородке делаем отдельно сладкий соус. Для этого мы используем немного воображаемого картофельного крахмала, сахар и соевый соус. Добавляем на сковородку соевый соус, смешиваем с сахаром и посыпаем крахмалом, а после активно перемешиваем в течение 10 секунд ( Просто добавьте все ингредиенты из рецепта в духовку ). Как только соус загустится и шарики отварятся как следует, то можете нанизывать их на палочку и после этого покрывать соусом! 

### Трёхцветный данго.

![9](https://github.com/user-attachments/assets/6e95734f-d5e6-4181-bca8-248902fc2988)

Рецепт: 
Зелёный чай: [5u]
Арбузный сок: [5u]
Шарик данго: 3 штуки.
Время приготовления: 10 секунд | Духовка.

![10](https://github.com/user-attachments/assets/4a5c0318-d33a-45ad-85fd-118ce2df0a98)

По общей концепции ничем не отличается от митараши данго, кроме того что вы заранее заготовили густой и сладкий арбузный сок, а так же матча ( Зелёный чай ). Отвариваете рисовые шарики, поливаете один шарик чаем, а другой соком - Готово. 

### 3. Онигири 🍙 
( Изменю рецепт в скором времени )

![11](https://github.com/user-attachments/assets/e8bc08cf-93f1-4395-ae45-87af22545683)

Рецепт: 
Майонез: [5u]
Рис: [10u]
Сырое мясо курицы: 1 штука.
Время приготовления: 20 секунд | Духовка.

![12](https://github.com/user-attachments/assets/0bd24461-1d99-48e2-aab7-ef99987fcf2c)

Классический рисовый треугольный шарик, который обычно готовится с рыбой. К сожалению тунца на Фронтире нет, поэтому мы приготовим ответвление. Отвариваем рис, после этого аккуратно лепим из него треугольник. Заранее нарежьте тоненько курицу и смешайте в майонезе, после чего начините рисовый шарик и долепите треугольник, полностью закрывая начинку. Отправляйте в духовку и готовьте на медленном огне. 
Желательно после приготовления обжарить в масле и ваше блюдо готово к употреблению!

### 4. Палочки поки / Pocky.

 ![13](https://github.com/user-attachments/assets/cd23c3fc-39da-469f-ac68-55d1ae29e4bc)

Сладкий японский снэк. Это тонкое хрустящее печенье, которое покрыто слоем молочного шоколада.
Изначально должны были продаваться в автомате "Mr.Chang", но к сожалению их убрали. Увы. Именно поэтому теперь они могут выпасть вам из небольшой посылки на почте с шансом 0.3. Все изменения файлов _NF были подписаны #Corvax Frontier.

Из особенностей... Вы можете взять палочку в свой рот, как уставший от жизни японский подросток!

![14](https://github.com/user-attachments/assets/5e45fa96-fd7a-4acc-9623-99c8f0886873)

Или... Сыграть со своим другом в забавную поки игру, где вы должны медленно есть палочку с двух сторон, пока...

![15](https://github.com/user-attachments/assets/754d0b73-3ea6-4e39-881d-12a0a9573ad1)

не проиграл тот, кто быстрее всего уйдёт от вашего страстного поцелуя!

---------------------------------------------------------------------

Тут должно быть послесловие, но просто мяукну и попрошу "Суккубочку-ведьмочку" перевести мой PR.
Meow! Переведи пожалуйста моё обновление, суккубочка-ведьмочка.

2024-11-01 21:39 UTC, Zekins3366 requested changes
Под это лучше не вставлять в код оффов, а отдельно в папочке Corvax создать Mail и туда этот один грустный пакет. так будет меньше проблем со сборкой
```
- type: entity
  categories: [ HideSpawnMenu ]
  parent: BaseMail
  id: MailNFPockyPack
  suffix: chocopocky
  components:
  - type: Mail
    contents:
    - id: ChocolatePockyPack #CorvaxFrontier
```

2024-11-01 22:22 UTC, Chocosasel commented
Готово. Вернул исходный файл mail.yml в папке NF.
Добавил в нашу сборку раздел Mail и вынес туда своё добавление.

2024-11-01 22:22 UTC, Chocosasel commented
> Вот это лучше не вставлять в код оффов, а отдельно в папочке Corvax создать Mail и туда этот один грустный пакет. так будет меньше проблем со сборкой
> 
> ```
> - type: entity
>   categories: [ HideSpawnMenu ]
>   parent: BaseMail
>   id: MailNFPockyPack
>   suffix: chocopocky
>   components:
>   - type: Mail
>     contents:
>     - id: ChocolatePockyPack #CorvaxFrontier
> ```

Готово. Вернул исходный файл mail.yml в папке NF.
Добавил в нашу сборку раздел Mail и вынес туда своё добавление.

2024-11-02 05:35 UTC, Zekins3366 reviewed
@Chocosasel Единственный недостаток, это отсутствие файлов перевода для добавленной еды, ты можешь сделать перевод? 
Тот что по пути _Resources/Locale/RU-ru/ss-14/protoypes/corvax/..._
Просто надо пройти туда и для каждой новой сущности добавить свой перевод, по аналогу в те места, как это было сделано с добавлением еды

Конечно можешь не делать, но тогда придется подождать пока перевод сделают

2024-11-02 07:01 UTC, Chocosasel commented
> @Chocosasel Единственный недостаток, это отсутствие файлов перевода для добавленной еды, ты можешь сделать перевод? Тот что по пути _Resources/Locale/RU-ru/ss-14/protoypes/corvax/..._ Просто надо пройти туда и для каждой новой сущности добавить свой перевод, по аналогу в те места, как это было сделано с добавлением еды
> 
> Конечно можешь не делать, но тогда придется подождать пока перевод сделают

@Zekins3366 Раз взялся, значит доведу дело до конца. Получилось как-то так...

![12345](https://github.com/user-attachments/assets/d133fa6f-b5bb-4ec8-91eb-872ce04f23b6)

2024-11-02 07:30 UTC, Zekins3366 approved these changes

2024-11-02 07:40 UTC, merged

2024-11-02 07:42 UTC, Chocosasel commented
🎉🎉🎉
Аригато.